name: deploy client to cloudflare

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create deployment
        uses: tomjschuster/cloudflare-pages-deploy-action@v0.0.10
        with:
          api-key: ${{ secrets.CLOUDFLARE_TOKEN }}
          email: ${{ secrets.CLOUDFLARE_EMAIL }}
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          project-name: ${{ secrets.CLOUDFLARE_PROJECT }}
          
