name: deploy client to s3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET }}
        aws-region: eu-central-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      working-directory: ./client
      run: npm install

    - name: Build
      working-directory: ./client
      run: npm run build:prod

    - name: Deploy
      working-directory: ./client
      if: success()
      run: aws s3 sync ./dist/missing-times s3://missing-times
