name: Deploy Client
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: VERCEL_TOKEN
          vercel-project-id: VERCEL_PROJECT_ID
          vercel-org-id: VERCEL_ORG_ID
