name: deploy client to cloudflare pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: deploy
        uses: Cyb3r-Jak3/actions-cloudflare-pages@v1.0.1
        with:
          account: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          project: ${{ secrets.CLOUDFLARE_PROJECT }}
          email: ${{ secrets.CLOUDFLARE_EMAIL }}
          global_token: ${{ secrets.CLOUDFLARE_TOKEN }}
